/** Tailwind configuration for frontend */
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#a8c8ff',
        'on-secondary-fixed-variant': '#2b486c',
        'on-secondary-fixed': '#001c39',
        'surface-container-low': '#131b2e',
        'surface-dim': '#0b1326',
        'on-surface-variant': '#c3c6d1',
        'error-container': '#93000a',
        'on-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        'on-secondary': '#123154',
        'primary-fixed-dim': '#a8c8ff',
        'on-tertiary': '#31312b',
        'on-primary': '#003061',
        'on-tertiary-fixed': '#1c1c17',
        'tertiary-container': '#706f68',
        'inverse-primary': '#385f97',
        'surface-container-lowest': '#060e20',
        'inverse-surface': '#dae2fd',
        'primary-container': '#4a70a9',
        'on-tertiary-container': '#f6f3ea',
        'surface-container-highest': '#2d3449',
        'outline-variant': '#434750',
        'on-primary-fixed-variant': '#1c477d',
        'on-primary-container': '#f0f3ff',
        'on-error': '#690005',
        'on-tertiary-fixed-variant': '#484741',
        error: '#ffb4ab',
        'tertiary-fixed-dim': '#c9c6be',
        'surface-variant': '#2d3449',
        'surface-bright': '#31394d',
        'on-background': '#dae2fd',
        'on-secondary-container': '#9bb7e0',
        background: '#0b1326',
        surface: '#0b1326',
        'tertiary-fixed': '#e5e2d9',
        secondary: '#acc8f3',
        'on-error-container': '#ffdad6',
        'surface-container': '#171f33',
        'primary-fixed': '#d5e3ff',
        outline: '#8d919b',
        'on-primary-fixed': '#001b3c',
        primary: '#a8c8ff',
        'surface-container-high': '#222a3d',
        'secondary-fixed': '#d3e3ff',
        'secondary-fixed-dim': '#acc8f3',
        'secondary-container': '#2b486c',
        tertiary: '#c9c6be',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.75rem',
        full: '9999px',
      },
      fontFamily: {
        headline: ['Manrope', 'system-ui', 'sans-serif'],
        body: ['Inter', 'system-ui', 'sans-serif'],
        label: ['Inter', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [],
};

